### PR TITLE
update aigle version

### PR DESCRIPTION
**Pull request by suguru03**
I improved `Promise.resolve` and some function performances.
Could you try latest version? :)

### CODE REVIEW

**Comment by icebob** [comment]
Great, thanks!

**Comment by icebob** [comment]
## Before with v1.1.0
```
   No promise*                                    0%     (14,438,184 rps)   (avg: 69ns)
   ES6 Promise.resolve*                      -97.24%        (398,947 rps)   (avg: 2μs)
   ES6 new Promise*                          -90.98%      (1,302,966 rps)   (avg: 767ns)
   Bluebird Promise.resolve*                 -82.72%      (2,495,574 rps)   (avg: 400ns)
   Bluebird Promise.resolve + 5 x then*      -96.05%        (569,827 rps)   (avg: 1μs)
   Bluebird new Promise*                     -78.12%      (3,159,209 rps)   (avg: 316ns)
   Aigle Promise.resolve*                    -84.41%      (2,250,622 rps)   (avg: 444ns)
   Aigle Promise.resolve + 5 x then*         -95.77%        (611,143 rps)   (avg: 1μs)
   Aigle new Promise*                         -78.6%      (3,090,121 rps)   (avg: 323ns)
```

## After with v1.2.0
```
   No promise*                                    0%     (14,218,838 rps)   (avg: 70ns)
   ES6 Promise.resolve*                      -97.15%        (404,630 rps)   (avg: 2μs)
   ES6 new Promise*                           -91.1%      (1,265,768 rps)   (avg: 790ns)
   Bluebird Promise.resolve*                 -83.22%      (2,386,485 rps)   (avg: 419ns)
   Bluebird Promise.resolve + 5 x then*      -96.08%        (557,818 rps)   (avg: 1μs)
   Bluebird new Promise*                     -77.84%      (3,151,063 rps)   (avg: 317ns)
   Aigle Promise.resolve*                    -77.16%      (3,246,915 rps)   (avg: 307ns)
   Aigle Promise.resolve + 5 x then*         -95.31%        (666,653 rps)   (avg: 1μs)
   Aigle new Promise*                        -78.41%      (3,069,287 rps)   (avg: 325ns)
```

Your improve was success :) +30% on `Promise.resolve`.
Maybe could you improve the `new Promise` too? :)

**Comment by suguru03** [comment]
Maybe almost same? 🤔 
I'll try to improve it. :)

v1.2.0
--
```
   No promise*                                    0%     (18,559,420 rps)   (avg: 53ns)
   ES6 Promise.resolve*                       -96.5%        (649,794 rps)   (avg: 1μs)
   ES6 new Promise*                          -92.73%      (1,348,395 rps)   (avg: 741ns)
   Bluebird Promise.resolve*                 -85.79%      (2,636,883 rps)   (avg: 379ns)
   Bluebird Promise.resolve + 5 x then*      -96.75%        (602,909 rps)   (avg: 1μs)
   Bluebird new Promise*                     -78.74%      (3,946,330 rps)   (avg: 253ns)
   Aigle Promise.resolve*                    -80.05%      (3,701,787 rps)   (avg: 270ns)
   Aigle Promise.resolve + 5 x then*         -95.92%        (756,825 rps)   (avg: 1μs)
   Aigle new Promise*                        -78.63%      (3,966,870 rps)   (avg: 252ns)
```

**Comment by icebob** [comment]
Ohh, I didn't see it is same as Bluebird new Promise :) Sorry

**Comment by suguru03** [comment]
Don't say sorry. :) 
It is good point, I'll look into it.
I didn't find `Promise.resolve` was slower. I appreciate your testing. 😄

**Pull request merged**
